import importPlugin from "eslint-plugin-import-x";
import stylistic from "@stylistic/eslint-plugin";
import love from "eslint-config-love";
import prettier from "eslint-plugin-prettier/recommended";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));

export default [
  { ignores: ["**/node_modules/**", "**/out/**", "**/*.d.ts", "server/tree-sitter/grammar/**"] },
  {
    ...love,
    plugins: { ...love.plugins, "import-x": importPlugin, "@stylistic": stylistic },
    files: ["client/src/**/*.ts", "server/src/**/*.ts", "server/scripts/**/*.ts", "server/test/**/*.ts", "server/tree-sitter/*.ts"],
    languageOptions: {
      ...love.languageOptions,
      parserOptions: {
        tsconfigRootDir: root,
        projectService: false,
        project: ["./client/tsconfig.json", "./server/tsconfig.json", "./server/tsconfig.eslint.json", "./server/tree-sitter/tsconfig.json"],
      },
    },
    rules: {
      ...love.rules,
      "import-x/export": ["error"],
      "import-x/first": ["error"],
      "import-x/no-absolute-path": ["error", { esmodule: true, commonjs: true, amd: false }],
      "import-x/no-duplicates": ["error"],
      "import-x/no-named-default": ["error"],
      "import-x/no-webpack-loader-syntax": ["error"],
      "@typescript-eslint/no-redeclare": ["error", { builtinGlobals: false }],
      "@typescript-eslint/no-var-requires": ["error"],
      "@typescript-eslint/no-empty-object-type": ["error", { allowInterfaces: "with-single-extends" }],
      "no-undef-init": ["error"],
      "prefer-promise-reject-errors": ["error"],

      // Preserve the existing lint policy when replacing standard-with-typescript.
      "@eslint-community/eslint-comments/require-description": "off",
      "@typescript-eslint/await-thenable": "off",
      "@typescript-eslint/class-methods-use-this": "off",
      "@typescript-eslint/consistent-indexed-object-style": "off",
      "@typescript-eslint/consistent-type-exports": "off",
      "@typescript-eslint/consistent-type-imports": "off",
      "@typescript-eslint/init-declarations": "off",
      "@typescript-eslint/max-params": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-deprecated": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-magic-numbers": "off",
      "@typescript-eslint/no-misused-spread": "off",
      "@typescript-eslint/no-redundant-type-constituents": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-unnecessary-parameter-property-assignment": "off",
      "@typescript-eslint/no-unnecessary-type-conversion": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-enum-comparison": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-type-assertion": "off",
      "@typescript-eslint/no-unused-private-class-members": "off",
      "@typescript-eslint/prefer-destructuring": "off",
      "@typescript-eslint/prefer-find": "off",
      "@typescript-eslint/prefer-promise-reject-errors": "off",
      "@typescript-eslint/prefer-regexp-exec": "off",
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/strict-void-return": "off",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
      complexity: "off",
      "max-depth": "off",
      "max-lines": "off",
      "max-nested-callbacks": "off",
      "no-await-in-loop": "off",
      "no-console": "off",
      "no-loop-func": "off",
      "no-negated-condition": "off",
      "no-param-reassign": "off",
      "no-plusplus": "off",
      "no-promise-executor-return": "off",
      "prefer-named-capture-group": "off",
      "prefer-object-has-own": "off",
      "prefer-template": "off",
      "promise/avoid-new": "off",
      "promise/prefer-catch": "off",
      "require-unicode-regexp": "off",

      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/naming-convention": ["warn", { selector: "variableLike", leadingUnderscore: "allow", trailingUnderscore: "allow", format: ["camelCase", "PascalCase", "UPPER_CASE"] }],
      "@typescript-eslint/no-non-null-assertion": "warn",
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/strict-boolean-expressions": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/consistent-type-assertions": "off",
      "@typescript-eslint/no-extraneous-class": "off",
      curly: "warn",
      eqeqeq: "warn",
      "no-unsafe-finally": "warn",
      "prefer-const": "warn",
      "no-extra-boolean-cast": "off",
    },
  },
  {
    ...prettier,
    rules: { ...prettier.rules, "prettier/prettier": ["error", { endOfLine: "auto" }] },
  },
  {
    files: ["**/*.ts"],
    rules: {
      curly: ["warn", "multi-line"],
      "@stylistic/lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
      "@stylistic/spaced-comment": [
        "error",
        "always",
        { line: { markers: ["*package", "!", "/", ",", "="] }, block: { balanced: true, markers: ["*package", "!", ",", ":", "::", "flow-include"], exceptions: ["*"] } },
      ],
    },
  },
];
