export enum LanguageTypes {
  int = "int",
  string = "string",
  object = "object",
  struct = "struct",
  action = "action",
  effect = "effect",
  event = "event",
  float = "float",
  itemproperty = "itemproperty",
  location = "location",
  talent = "talent",
  vector = "vector",
  void = "void",
  json = "json",
  sqlquery = "sqlquery",
  cassowary = "cassowary",
  none = "none",
}
