name: Tests

on:
  pull_request:
  push:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        uses: borales/actions-yarn@v3
        with:
          cmd: install
      - name: Run Tests Suite
        uses: borales/actions-yarn@v3
        with:
          cmd: test
